version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/tasksdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend
    ports:
      - '3000:80'

volumes:
  mongo-data:
